name: homeli
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hugeicons: ^1.1.7
  flutter_launcher_icons: ^0.14.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.8

flutter_launcher_icons:
  android: true
  image_path: "assets/icons/Homeli Logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#04123F"
  adaptive_icon_foreground: "assets/icons/Homeli Logo Transparent.png"

flutter_native_splash: 
  color: "#04123F"
  image: "assets/icons/Homeli Logo Transparent.png"
  android: true

flutter:
  uses-material-design: true

  assets:
     - assets/images/
     - assets/icons/
     - assets/fonts/

  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700